# Generated by Django 5.0.3 on 2024-06-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
